### ISSUE TITLE
Datapack-added Textures Working Sporadically

### ISSUE THREAD

**Issue by katubug** [SilentChaos512/Silent-Gear#183]
## Versions

- **Silent Gear**: 1.10.0+131
- **Silent's Gems**: N/A
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.31
- **FutureMC**: 1.0.1
- **Kotlin For Forge**: 1.3.1
- **Modpack**: N/A
- **Optifine Installed**: No

## Description
Hi! We spoke on Discord yesterday. I have done some more testing, and found that I was able to replicate the issue in an instance with only Silent Gear, Silent Lib, and the mods required for the datapack. I have replicated it with both Gems N Jewels and FutureMC separately, but for this ticket I'll be using the example for Netherite from FutureMC.

The issue is that when making an axe from the datapack'd material, the head texture goes missing once a rod is added. I haven't tested this with other gear, but my guess is that it's a similar story.

## Images
A Netherite Axe Head - 
![2020-07-22_11 22 44](https://user-images.githubusercontent.com/20935286/88202497-933bce00-cc0e-11ea-9145-301add4a705c.png)

The axe with a rod added - 
![2020-07-22_11 22 48](https://user-images.githubusercontent.com/20935286/88202523-9fc02680-cc0e-11ea-8a07-9abd429f2a26.png)

The finished tool while wielded - 
![2020-07-22_11 23 09](https://user-images.githubusercontent.com/20935286/88202543-a6e73480-cc0e-11ea-80db-8de73f00659f.png)

## Logs etc

Here is the latest.log file for this incident: https://pastebin.com/BTmBLg51

Here is the datapack json, copied from Just Metals' Titanium and tweaked: https://pastebin.com/bJbCCdqa

Here is the `/sl_nbt item` output for the axe: https://pastebin.com/wHucGyHc

Please let me know if I can provide any other information!

**Comment by Sinhika** [comment]
I am running into the same problem. I am trying to add Silent Gear support to SimpleOres, due to user requests; I have added material data and model jsons as per the Wiki instructions, copying from Silent Gear materials to make sure I got the format right. If I make, e.g. an adamantium axe head, I can hold it in my hand and see it. As soon as I add a rod and turn it into a tool, it is invisible when held in hand. This does not happen with custom rods, btw. If I craft an mythril rod and combine it with an iron head, it displays as it ought to when held.

Is there a workaround for this? Am I missing something from the datapack?

**Comment by Sinhika** [comment]
Seeing the same problem in 1.16.4: If I make a custom material (from SimpleOres) tool head (tested with adamantium and mythril), I can see it in my hand. However, as soon as I combine it with a rod to make a tool, the tool becomes invisible!  This does not happen with custom material tool rods however, or materials that are already spec'd in Silents Gear such as copper and tin. You can see my data files at https://github.com/Sinhika/SimpleOres2/tree/1.16.4_w_silentgear. What am I doing wrong, or is this a bug?

**Comment by SilentChaos512** [comment]
Might be fixed in version 2.3.7

**Comment by Sinhika** [comment]
Okay, new data. Bug is not fixed, BUT... the bug only appears in 1st person view. If I use F5 and look at the toon from various angles while holding the tool, the tool made of custom materials is visible.

To sum up: in 1.16.4, in your latest 2.3.7 hotfix, the tool is wholly invisible in the following conditions:

1.  The tool head is made from a custom datapack material, such as Simple Ores' mythril.
2.  The character viewpoint is 1st person.

Otherwise, the tool is normally visible.  Silent Gear material for tool head, custom material for tool rod: visible. Any combination of tool materials, NOT in first person: visible.

To help you debug this, I will be putting up an alpha release of Simple Ores2 on CurseForge that has Silent Gear support.

**Comment by Sinhika** [comment]
Test version that I've been using with datapacks for silent_gear: https://www.curseforge.com/minecraft/mc-mods/simpleores/files/3115783

**Comment by SilentChaos512** [comment]
@Sinhika It seems the reason your tools are invisible in first person is because of the -2.4 attack speed modifier on mythril and adamantium. On a pickaxe, that produces an attack speed of zero, so it never gets lifted up. The attack speed should typically be +/- a few tenths. I guess I should also clamp the value so this doesn't happen.

**Comment by Sinhika** [comment]
Welp, that's weird side-effect of me half-assing the attack speed mods! I suppose I should revisit those one of these days.

**Comment by Sinhika** [comment]
Okay, so your attack_speed value *isn't* the ItemTier attack speed. What is it based on?

**Comment by Sinhika** [comment]
And that fixed my problem. However, your wiki entry on the attack_speed stat is very confusing and suggests that attack_speed is **supposed** to be negative in the data file. Please fix this.

**Comment by SilentChaos512** [comment]
Thanks, I updated the description to explain it a bit better. The attack speed on the material gets added to the base speed of the item, which is why it should be closer to zero.
