### ISSUE TITLE
Grader catalysts used before bound crash when loading resource packs. 1.16.1

### ISSUE THREAD

**Issue by mettlephaontoms** [SilentChaos512/Silent-Gear#224]
## Versions
1.16.1

- **Silent Gear**: x.x.x SilentGear-1.16.1-2.1.1+162
- **Silent's Gems**: x.x.x SilentGems-1.16.1-3.6.3+100
- **Silent Lib**: x.x.x SilentLib-1.16.1-4.7.0+58
- **Forge**: x.x.x 1.16.1-forge-32.0.108
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior
Resource pack loads and only changes vanilla textures.

## Actual Behavior
Resource pack tries loading twice, then crashes.

## Links/Images
https://pastebin.com/uFi4pT0T

## Steps to Reproduce the Problem

1.Get resource packs 
2.Insert them into the resource packs folder
3.Load a resource pack after the game has launched.

**Comment by SilentChaos512** [comment]
Does it crash without Optifine?

**Comment by mettlephaontoms** [comment]
Yes, it crashes without optifine.

**Comment by ghost** [comment]
Can confirm this crash, with and with out optifine + optiforge
https://pastebin.com/vj6VsbQL

this is happening everytime to one of my friends and most times for me.
We are both assigning enough ram and have very uptodate systems

Edit:
Forge 34.1.1 (also tested 34.1.5)
Launcher GD Launcher (using its installed java)

SilentGear-1.16.3-2.2.0+164
SilentLib-1.16.3-4.8.1+61

Disabling the two above and i can change the resource packs fine (just tried 3 times in a row, no crash)

Edit 2:
Just got my friend who crashes every time to try disabling the mods above and he can now select resource packs again. 

is this an old bug that was fixed and broke again or a bug that only effects a small number of people (can see theres been a few versions since this was originally reported) ?

**Comment by SilentChaos512** [comment]
Thanks for the updated crash report. This bug was never fixed, honestly not sure how to. Seems that Apotheosis is generating item tooltips before item tags are ready or something? At least that's what the crash report makes it look like.

I guess I could just remove the grader catalyst tooltip line for now, which _might_ fix the crash.

(edit) Well I just tried with an instance of just JEI, Gear/Lib, and Apotheosis/Placebo. No crash when changing resource packs. So maybe the issue is more complicated than that.

**Comment by ghost** [comment]
My first thought was that it should not be a mod issue as they are vanila textures but its becoming a rather nasty issue for our little group (some of whom have got too used to the texture packs they use clarity-32 i think is the one) However removing the mod and the library immediately solves the issue.

Got to hate bugs that can not be replicated, they are the worst to fix, the only way i can think to help replicate it is if i link you to a copy of our instance? this is imported into GD Launcher and would give you the exact same set up that is effecting myself and one of our other group members?

**Comment by ghost** [comment]
the instance mentioned above: https://we.tl/t-sKUz2V64vu

**Comment by ghost** [comment]
No 150 mb log here, just recreated the crash.
40mb debug log (most of that is kubjs not finding recipies, part of all of the mods 6 pack, though we  have deviated a lot from that pack since)

we are using a fair few mods with custom tool tips (including mekenism dev build which has the whole "hold shift +n to see this and shift to see that") Not saying its not your tooltip...this is minecraft and what should work does not always actually work lol just that we do have a lot of custom tool tips

**Comment by ghost** [comment]
Did find a work around (and this is confirmed to work for others too)

1) disable silent gear and lib
2) load the game
3) choose resource pack of choice
4) close game
5) enable silent gear and lib
6) load game with shinny resource pack now working
7) dont touch resource pack options....treat it like a radioactive bunny rabbit....

ok not ideal but atleast anyone wandering into this issue page can see a viable work around...

now...what is it doing perfectly fine to load your mod with resource packs while starting that it is not doing when the resource pack is changed lol (no idea if forge api gives you any hooks to use when a resource pack i changed but may be a solution there somewhere)
