### ISSUE TITLE
Add config option to make repair kits optional

### ISSUE THREAD

**Issue by clarity2199** [SilentChaos512/Silent-Gear#316]
Silent Gear/Silent Lib 1.16.3/1.16.4 with Forge
Optifine not installed

I don't know if this is a bug or not, or maybe a config tweak. Not sure where else to put this but I would like a solution how to fix this. 

I've used Silent Gear in Team Rustic. In that modpack you can use the raw material to fix the item, which I was able to do in past Silent Gear mods before they even had a toolbox. But in any other new 1.16 modpack I've played, for some reason I have to use a toolbox, which I simply don't like the feature. I like using Silent Gear for early game and moving into Botania after. If I have to fight with these stupid gear boxes, then it's not worth using the mod for me.

The question is how to make this mod work like Team Rustic, where I only need the raw materials and not the tool boxes?

Please don't give me an opinion on the tool boxes! I'm sure some people love them. I'm not putting it down for other people, this is simply my personal opinion. I'm just looking for a solution.

I have tried removing both the mods and configs and replacing it with the one from Team Rustic in order to fix it. Sometimes that actually works, but sometimes it doesn't. 

Is there some kind of config tweak I have to adjust, or maybe you have an in-game command which can change this? Please let me know. Thank you!

Team Rustic uses a 1.16.3 version. I have used every other version for 1.16 in modpacks and none of the others seem to offer me the ability to repair it with raw materials. Exchanging them out to the 1.16.3 version and configs sometimes helps, but it's not consistent.

**Comment by SilentChaos512** [comment]
Please follow the issue template next time, it exists for a reason. I have no idea which mod versions you are talking about because of this. And no, the Minecraft version does not help at all. The mod is still in active development and changing constantly.

I assume you are talking about **repair kits**. Those are a feature, not a bug. They were introduced in version 1.8.1 (MC 1.15.2) and have been required since then. No build I have released for 1.16.x has _not_ required them. Most users seem very happy with them, aside from the initial confusion when they were introduced.

Since the repair recipe is dynamic, this would require code changes to make possible. So, you should have made this a feature request. I think this would be fairly easy to implement. The recipe already looks for loose materials, like the old one, so I guess I could "trick" it into believing an empty repair kit is also in the crafting grid.

**Comment by clarity2199** [comment]
I apologize, I am not very good with computers. I figured I was probably in the wrong category, but I'm rather new on GitHub, so I had no idea how to reach the category I needed to go. I'm sure you're probably used to dealing with kids. I'm around 50, so learning new things isn't easy for me. Well, if it's not possible, I don't know how it was done, but the Team Rustic modpack seemed to succeed in doing so somehow under Curse. I am not criticizing the mod, as I tried to explain, this is my personal preference, I was simply used to the old system and it was so much easier throwing in the ores and fixing it.
If the way to get this is to request that as a config option, then yes.....I am requesting that. Thank you very much for listening, you have a very good mod.

**Comment by SilentChaos512** [comment]
Sorry, I could have chosen my words better yesterday. I should know better than to write responses when I'm in a bad mood. I'll make sure the new option gets into the next version, assuming I don't run into any unexpected issues. It will likely be in the same place as the repair kit efficiency configs in `silentgear-common.toml`.
