### ISSUE TITLE
Simple Exploit

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silent-Gear#37]
If you craft 9 fragments of any type then use those to craft back the item, it resets the grade.
This allows for resetting the grade until it reaches SSS.

A possible fix would be to make analyzed items keep there respective grade between blocks and fragments.

**Comment by SilentChaos512** [comment]
This is an issue I have been aware of for a long time (since grading was introduced in Silent's Gems), and I've never been that concerned about it. I suppose it would be possible to copy the NBT, since there is an "item crafted" event provided by Forge. But I have no idea how I could check that the grade on all the shards actually matches, and prevent crafting in that case. As far as I know, that would require custom recipe types, and that would only fix _my mods_.

I wouldn't mind adding a config if I could ever come up with a solution, but I'm not sure if that's even possible.

**Comment by ghost** [comment]
I ended up dubbing this a feature. "Calling this a refining process."
Deconstructing and reconstructing the shape to fit better quality standards.
Nice mod btw!

**Comment by Syndaryl** [comment]
I've been poking at this "issue" for a while and going back and forth over it. I don't think it's a major problem, as it's an incredibly labor intensive process (JEI crafting accelerators aren't helping much) and the grading process takes so long, and is pretty random.
It can be improved by combining with a bunch of automation from other mods, but the parts grader is still slow.

I'm going to vote also for "feature, not a bug". Or at least, "not a bug".
