### ISSUE TITLE
JEI Search Tags

### ISSUE THREAD

**Issue by joey-drake** [SilentChaos512/Silent-Gear#386]
## What Should Be Added or Changed?
A way to search JEI by materials used for a certain part. e.g. #main/elytra #binding etc... 

## Why Should This Be Done?
This would help when researching what material a user would like to use without having to dump it into a spreadsheet

**Comment by SilentChaos512** [comment]
This should already be possible, but you need to change a config option in
JEI. See here:
https://github.com/SilentChaos512/Silent-Gear/wiki/Starter-Guide#in-jei

**Comment by joey-drake** [comment]
oh perfect! Sorry I didn't see this in the wiki when looking through it. What would be the syntax to look for materials specific to a certain part?

**Comment by SilentChaos512** [comment]
Whatever searches tooltips. I think it was `#`? You can also search for
specific traits this way.

**Comment by joey-drake** [comment]
That worked! Thank you so much. Appreciate all your support for your community

**Comment by jmdev91** [comment]
Can this issue be revisited? In 1.18, in the ATM7 pack, I can only search by material usage (main, tool rod, adornment, etc.) when I've loaded the world by holding shift and ctrl (takes a while), and I cannot search for specific tiers because tooltip searches don't register spaces, even when quoted (#"tier 4" brings up all materials that have 4 somewhere in their stats). Would it be possible to have the mod generate tags so we could just search for relevant materials using something that works out-of-the-box?
