### ISSUE TITLE
Shears breaks all blocks fast

### ISSUE THREAD

**Issue by fourglobe302500** [SilentChaos512/Silent-Gear#411]
## Versions
1.16.5

- **Silent Gear**: 2.6.30
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.65
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

breaking blocks with a certain time when is the expecifed tool type

## Actual Behavior

* inta-mine vines (shoud't do that)
* breaks almost any hand-breakable block in an instant
* mines all blocks extremally fast (~10 sec to break a obsidian)

## Steps to Reproduce the Problem

1. any shear (vannila included)
2. any block

**Comment by Shorepion** [comment]
Experienced the same.
Modpack: https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii
(Also trying a new instance with only SilentGear installed, have the same result).

**Comment by PhoenixEvolver** [comment]
Can confirm this bug still exists

## Versions
1.16.5
 
* **Silent Gear**: 2.6.35
* **Silent Lib**: 4.10.0
* **Forge**: 36.1.00
* **Modpack**: N/A
* **Optifine Installed**: Yes
 
## Expected Behavior
Vanilla and Crafted variants of sheers should exclusively decrease the amount of time to harvest specific blocks[https://minecraft.fandom.com/wiki/Shears#Usage](url)

## Actual Behavior
* Mining speed on certain blocks is on par with various diamond-effective tools. possibly even netherite-coated diamond tools
 
## Steps to Reproduce the Problem
1. Obtain any shear, vanilla, or Silent gear crafted
2. Hold in Hotbar
3. Use shears to mine any breakable block

## Bonus
/give @p minecraft:shears{Unbreakable:1}

**Comment by jinkhya** [comment]
Same problem here, you can even mine marble from chisel with bare hands :)

**Comment by SilentChaos512** [comment]
Observed the issue with vanilla shears as well... But only with Silent Gear installed. Seems to be an improperly coded event handler on my part.
