### ISSUE TITLE
1.17.1 Fishing rod immediately returns after casting, unable to fish

### ISSUE THREAD

**Issue by GhostieEcho** [SilentChaos512/Silent-Gear#425]
## Versions
 Minecraft 1.17.1
- **Silent Gear**: 2.7.2
- **Silent's Gems**: 4.1.2
- **Silent Lib**: 5.0.0
- **Forge**: 37.0.50
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior
Floatie to go out onto the water, bob like usual, catch fish.

## Actual Behavior
Floatie immediately comes back in, unable to fish.  Built a vanilla fishing rod to test, and it works as intended.

My Silentgear fishing rod is built with Iron main, Birch rod, and fluffy string bowstring.

Same result with a fishing made with birch main, string bowstring, and stone rod.

## Steps to Reproduce the Problem

1. Build a fishing rod like mine.
2. Go to a lake etc
3. Try to fish.

**Comment by SilentChaos512** [comment]
Mostly just some notes for myself: Seems to be caused by some vanilla code that kills the fishing hook entity whenever the held item is not a vanilla fishing rod. I think the only solution right now since we have no Mixins would be to extend the `FishingHook` entity and override the relevant method.

**Comment by Syndaryl** [comment]
Oh is *THAT* why everyone has the same trouble with custom fishing rods? useful knowledge!
