### ISSUE TITLE
1.17.x metal mixing not supported?

### ISSUE THREAD

**Issue by McKitten** [SilentChaos512/Silent-Gear#447]
This has been noticed in Towncraft Three (which i wrote off because the pack is a mess) and now ATM 7.
Both are 1.17 but beyond that have nothing in common bar the lack of opti-crap.

## Expected Behavior

Expect to be able to mix metals whilst using a blueprint. A chestplate has 8 slots and they all have to be the same metal type (not even same tier works). This applies to every blueprint yet (i.e. haven't tried fishing rod or paxel) tho will allow rods of different mats.

**Comment by SilentChaos512** [comment]
I'm surprised this is the first time this has been brought up on GitHub, unless I missed something. Let me explain.

That feature is now disabled by default. The config option was also renamed to force the switch, so copying an old config file won't change it. Material mixing is so powerful, I decided to lock it until later in the game, which is why the compound-making machines (metal alloyer, etc.) exist. It's the whole reason they were added. That also has other restrictions, like only allowing some categories of materials (metals, gems, cloths/fibers) to be mixed. No overpowered early-game mixed stone tools.

How to change (this is pinned on Discord):

> To re-enable the old material mixing system, you must change the `allowLegacyMaterialMixing` config option in `silentgear-common.toml` to `true`.

If that config option is enabled, the crafting system works exactly like it used to. I encourage playing without it, but that's your decision to make.

**Comment by SilentChaos512** [comment]
Added a hint to the config in blueprint tooltips with 54fd0ff74d3cf1419a252cc55e36b387f8d3639a. That should help future players.

**Comment by TheRealTwinPEaks** [comment]
tried to modify this, couldn't find the setting at all. checked all of the config files and couldn't see it. could you provide a file path perhaps?

**Comment by osirisgothra** [comment]
Funny, i ended up here _because_  of that tooltip and wondered what it meant. I see now, sounds like it almost became dartcraft but then realized they better not. Dartcraft was the very pinnacle of the too-much/too-soon/too-easy OP when it came to equipment--it is no wonder every other tool mod would avoid that mistake. 

You are probably scratching your head "so what _is_ dartcraft???". That's the point, nobody knows anymore. Because of its crazy OP-ness it became shunned by many of the other mod devs and then forgotten and never mentioned except in these rare instances where someone who actually once used it wants to shame it once more. It wasn't so much a bad mod all in all, if I had to explain it simply, I'd say it was like draconic evolution except instead of draconium, dragons and comets, you were just using materials you could get from the first 5 minutes of play. Yeah, and I'm not even exaggerating either. Glad this author chose to avoid walking that dangerous path of OP-ness.
