### ISSUE TITLE
Mattock Not Working To Till Earth

### ISSUE THREAD

**Issue by BenPharris** [SilentChaos512/Silent-Gear#502]
Right click functionality not working with the mattock to till farmland. Mods installed : aquaculture 2, botania, curios API, farmer's delight, JEI, Patchouli, Terralith.

**Comment by BenPharris** [comment]
Also tried multiple attempts at changing keybind behavior and no luck

**Comment by SilentChaos512** [comment]
Follow the bug report issue template. I need to know the version numbers for my mods.

**Comment by Eonasdan** [comment]
This is an issue for me on silent-gear-1.18.2-2.10.0

**Comment by SilentChaos512** [comment]
Tested this with just Silent Gear, and I see no issues.

First, make sure that your mattock has no traits that are overriding its right-click behavior. If that is what is happening, your need to tweak your item. If it is doing nothing at all, you have a mod that is breaking mine.

Issues like this one are usually caused by other mods. You need to figure out which mod on your mod list is causing the conflict, then ask the author about it.

**Comment by Talcall** [comment]
I am thoroughly testing this issue, as I can verify one or more mods is causing an issue with the tilling functionality of mattocks (silent gear 2.10.0, silent lib 6.2.0)
My mod list is considerably longer, and does *not* include the following on Ben's list:
Patchouli, terralith, botania, curios api.
Through individual mod testing, the following base mods (mods requiring other mods are only considered if their base does not disable mattock tilling) disable the tilling of an iron mattock, handle minecraft:stick (crafted fresh on a new world each time):
Farmer's delight (in Ben's list, by vectorwing) 
Aquaculture 2 (in Ben's list, by Shadowclaimer) 
Amplified Nether (by starmute)
AppleSkin (by squeek502)
AutoRegLib (by Vazkii)
Better Azalea (by SameDifferent)
TerraBlender (by TheAdubbz)
Blueprint (by TeamAbnormals)
Clumps (by Jaredlll08)
Flywheel (by jozufozu)
I like wood (by yamahari_)
Incendium (by Starmute et. al)
JourneyMap (by techbrew)
Just Enough Items (JEI) (by mezz)
I am too tired to test further in this regard. But with a mod list this large, it seems impractical and inconsiderate to contact every author to request them to check compatibility with your mod. 
Especially since the issue is with your mod. Using silent gear (up to date) and silent lib (up to date) only (as well as forge and minecraft) does not have functional mattocks.
Please give this another look.

**Comment by SilentChaos512** [comment]
Thanks for testing. Guess I'll try creating a proper instance and retesting next time I'm at a computer (probably Saturday or Sunday if I'm lucky). But it worked normally when tested in a development environment. Not sure why that would be any different, unless a Forge update is causing a problem.

(edit) Speaking of Forge versions, I don't believe anyone here has shared what version they're using...

**Comment by BenPharris** [comment]
Apologies for slow response here using 1.18.2 / latest release version as of my post with silent gear 2.10.0 silent lib 6.2

I tested with iron and diamond mattocks and no dice, though not in any other mod configuration

**Comment by SilentChaos512** [comment]
Confirmed using Forge 40.1.0, Gear 2.10.0, and Lib 6.2.0. Perhaps Forge changed something in a recent update? I'll have to debug the issue when I get the chance.

**Comment by SilentChaos512** [comment]
The gear type was missing the HOE_TILL tool action from its definition. Easy fix.
