### ISSUE TITLE
Silent Gear is taking performance (as much as 20 fps)

### ISSUE THREAD

**Issue by Pixeluted** [SilentChaos512/Silent-Gear#602]
## Versions

- **Silent Gear**: 3.2.5
- **Silent Lib**: 7.0.3
- **Forge**: 43.2.11
- **Modpack**: All The Mods 8 - 1.0.18
- **Optifine Installed**: No

## Expected Behavior
Silent Gear, should not render every tick the traits on the as it takes too much performance (especially when running shaders),
or atleast option to disable this.

## Actual Behavior
Performance loss

## Steps to Reproduce the Problem

1. Preferably use some shaders (I used ComplementaryReimagined)
2. Take silent gear item into hotbar or just inventory

**Comment by Sciras** [comment]
I noticed a similar issue, before upgrading my graphics card a set of Silent Gear tools (any type really, and I don't think materials matter either) halved my fps, now it's a ~20% reduction. If it helps, here's a spark profile of my render thread:
https://spark.lucko.me/3k5hMSmnpJ
This is with having two Paxels, a Katana and a Bow+Arrow on the hotbar.
As part of the Forge GUI rendering, the (Item Interface).getColor() function call on each Silent Gear item appears to eat around 3-4% of total render time. And most of that time is spent on GearData.getConstructionParts(). 
I'm not familliar with Minecraft modding, but perhaps it would be possible to cache this? Seems like it's something that would only really need to be recalculated when the item is modified in the crafting grid.

Edit: This is on ATM8 1.0.19, Silent Gear version 1.19.2-3.2.5, Silent Lib version 1.19.2-7.0.3
And here is the relevant parts of spark, since I don't know how long they keep these reports online
![image](https://github.com/SilentChaos512/Silent-Gear/assets/135485886/41a248be-a387-4043-8d35-cf897b42f1e6)
