### ISSUE TITLE
1.20.x Elytra - Curios compatibility crash

### ISSUE THREAD

**Issue by Fraali** [SilentChaos512/Silent-Gear#611]
Version 1.20.x

Crashes if you equip an Elytra into a Curios slot with a reference to `fallFlyTicks`

Minecraft 1.20.1 (forge-47.0.34/forge)

Reference to
~\src\main\java\net\silentchaos512\gear\compat\curios\CurioGearItemCapability.java - Line 48

Old Value - "fallFlyTicks"
New Value - "f_20937_"

(Above compiled and confirmed to be working)
https://i.imgur.com/QEAbFgH.png

**Comment by Gbergz** [comment]
Bump, can confirm this issue!

Logs: https://gist.githubusercontent.com/Gbergz/5de4302f96a40f5877a22f6ca654cbeb/raw/fc0500fdd181c0ddd6eadcde481df27ab6b007e9/gistfile1.txt

**Comment by ewickly** [comment]
I've had this issue as well! They should NOT be able to be equipped in curios slot, because default elytra are not able to. That should fix the issue.

To anyone who has had this issue in a singleplayer world, edit the NBT data for you playerfile in the level.dat file not the player files. If it's a multiplayer world, modify the player.dat file. Should be under ForgeCaps, curios slot, and the back item. Just delete the entry containing ID back to fix it.

**Comment by ewickly** [comment]
Out of curiosity. Does the Caelus API stop this from happening? I noticed that when I did not have Caelus API installed, it said it was needed in the item description. I also noticed a modifier named Fall Fly attached to the Silent Gear Elytra. I'm going to go ahead and try to equip one now that I have added the API. It did not solve the problem for an already equipped SG Elytra, but I hope it solves the issue for future Elytra.

Edit:
Nope. Still crashed it.
