### ISSUE TITLE
Silent Gear Bow Uses Entire Silent Gear Arrow Stack

### ISSUE THREAD

**Issue by AlgebraManiacABC** [SilentChaos512/Silent-Gear#730]
## Versions

- **Silent Gear**: 4.0.4
- **Silent's Gems**: N/A
- **Silent Lib**: 10.3.0
- **Forge**: Neoforge 21.1.68
- **Modpack**: AllTheMods 10-1.0
- **Optifine Installed**: No

## Expected Behavior
Silent Gear bow should subtract from the silent gear arrow stack by one after firing

## Actual Behavior
Silent gear bow deletes all 64 arrows from stack upon firing.

## Links/Images
https://imgur.com/KN4baiR

## Steps to Reproduce the Problem
Make the bow and arrow (with the components described) and fire.

**Comment by DaddyLongspoon** [comment]
+ also the arrow cannot be repaired.  When you craft a silent gear arrow its durability is at one quarter (64 arrows) in past versions you could repair it in the crafting grid with repair kit and have the full bar (256 arrows).  
I'm adding this here because I expect it is related or the same bug (regarding arrow durability bar)

**Comment by Chifilly** [comment]
I can also confirm this. Just had it happen to me in ATM10. Exact same issue of un-repairable arrow with 64 arrows, and a single use destroys it.
