### ISSUE TITLE
1.15.x - Plans for part analyzer and grading

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/Silent-Gear#83]
Looking for some feedback on this. I am considering removing the grading system and part analyzer for 1.15.x. The reasoning for this is the grading system has an "exploit" (#37) which cannot be fixed. It's not a major issue, just an annoyance. You can "grind" out parts to get the grades you want.

I also understand some are just not fond of the grading system at all. Some configs were introduced to customize random grading, which can cut the randomness entirely, or fix it to a specific grade.

There's also some confusion on how grading works in some cases. Some expect it to work on tool heads or completed items, which is not how grading is meant to work.

So, removing grading were cut the stat bonuses, but also the penalties of low grades. Might add something else in or do some re-balancing to counter this, not sure. Absolutely exhausted after this past week, so hopefully that all made sense. (>_<)

**Comment by Partonetrain** [comment]
FWIW, I like the grading system, and I have always viewed the "exploit" as just re-rolling your grade and considered it a feature in my custom pack. With the config options, along with custom catalyst tags, this part of the mod is very pack-maker-friendly. 

However I have some negatives with it;
-For one it's called the "Part Analyzer", which makes it sounds like it analyzes Parts, like tool heads. I would change its name back to the Material Grader (Why was it changed?). 
-It is almost redundant with SGems Supercharging, but the stat improvements stacks with that (but in a modpack with just SGear it wouldn't make a difference).  
-The grades D & E are *worse* than the default, and I know that's intentional, but with the exploit there is no reason to keep the lower grades.

Still though, I would like to see this system in future versions, but improved.

**Comment by SilentChaos512** [comment]
One idea I had (which I forgot to mention in OP) is to replace the grading system with something more consistent, less random. Maybe a "crafting skill" that yields increasing better grades as players craft or repair gear. That would attach the grade to the final item, instead of the materials. Could also make playing on servers more interesting (some players could specialize in working with gear).

**Comment by Partonetrain** [comment]
I like it, or maybe tiered crafting tables that produce different grades of gear? Or tiered blueprints? There are a couple ways to go about this

**Comment by SilentChaos512** [comment]
Would prefer different tiers of gear crafting blocks over blueprints if I
go with that option. But I like the ideas.

If anyone else has ideas, feel free to chime in. This issue is an open
discussion. :)

**Comment by ProsperCraft** [comment]
Yes, this sounds great, cut the grading system.

I did like the randomness thought.

Crafting skill would be nice.

**Comment by Landstryder** [comment]
Instead of grading... gem cutting and polishing.... cutting could improve one set of stats and polishing a different set... could be done with the "Material Station" (just use the analyzer code mostly) and depending on what material you used in the working slot it could give a chance to improve the cut or clarity (or decrease it on a bad roll) but the process would be mostly repeatable (some kind of configurable chance to loose the gem in the process) until you got max stats or were satisfied with the result.

**Comment by Hexblood** [comment]
I like the idea of the skill system. Maybe there could be different skills to effect different things and when you "level up" you can assign a point to the one you want. Skills could be things like Attack, Defense, Durability, Speed, etc.

**Comment by torzod** [comment]
I think whatever the end result is should be toggleable via configs, so that you can disable it to get a more "vanilla" feel, which is what i would like most. no leveling, just gear. Leveling up by crafting just leads to tedious crafting of tons of gear you won't use as intermediates, and leveling up by "experience" just leads to farming/grinding, which is also tedious. Personally, I think that different materials should have different properties and benefits/drawbacks. for instance, gold has more enchantability in vanilla but its low durability makes it practically worthless. Making some high-level stuff be slow with high durability or vice versa would be insteresting. Maybe full armor sets could give you slight bonuses (like in Terraria or various other games)

Edit: perhaps some specific gear could give substantial bonuses and substantial drawbacks, making them specialized (i.e. the turtle shell from vanilla)

**Comment by Partonetrain** [comment]
The new system being grindy is a concern of mine too. The idea of repeatedly making a stone pickaxe for tool-making experience so I can have the optimal pickaxe seems silly. Silent, can you elaborate on what you had in mind for the skill system?

---

Expanding on my tiered tables idea, maybe multiple specialized tables for each stat? IE. Attack Gear Table I, Attack Gear Table II, Durability Gear Table I, etc etc

That would be more bloated than a skill system, but it's an option, especially if we are going for no/little grinding

**Comment by Hexblood** [comment]
He did mention that repairing would be part of the skill system so that takes some of the grind down. Maybe other elements could be added to the skill system. Like just using the Silent's Gear items could also be part of the system. Say having a decent chance of gaining skill experience each time a SG item loses a point of durability. 

Maybe also having a way to convert Vanilla experience into skill points could be good as well

-----

Now with the idea of having different tables. I am not a fan of having to have say half a dozen different tables to gain different effects on the crafting. Maybe having tiered quality of tables that can take different amounts of upgrades to influence the tools made in it. 

So say you start with the basic Crafting Station that has no upgrade slots. 

Next tier has one upgrade slot and you can stack up to 2 of the same upgrade in it. Made with classic set gems.

Next one has 2 slots and upgrades can stack up 4 each. Made with dark set gems.

Final tier has 3 slots and can stack up to 6. Made with light set gems.

Upgrade slots can go at the top of the GUI like on Silent's Mechanism's machines.

**Comment by Partonetrain** [comment]
True, this skill experience doesn't have to be made hard to get at all. In fact it could even be very configurable; this many skill points for level 3, each point of durability loss has a X chance of giving Y experience, all defined in config.

I'm undecided on which system I would prefer - skill or tables. Both of them sound fun.

---

I like the slot-upgrade idea a lot. Much better than having 3 tables for each stat. More interactive, too, making you think about which upgrades you want and don't want for one particular piece of gear.

Recipes can't use Silent's Gems items if the mods are going to be kept independent, though. 

Curious what Silent thinks and how/if either feature could be implemented

**Comment by Hexblood** [comment]
Fair point about the Silent's Gems. I use the two mods together so much I tend to think of them as the same mod. Derp on my part.

**Comment by ghost** [comment]
So the grading system is gone correct? If so, gem tooltips need to be updated as they still state "Grade: Not analyzed". I spent a solid hour trying to figure out how to grade the gems before searching online (I prefer to figure things out myself).

Are there any plans to reintroduce something? I personally like what @Landstryder proposed. Reminds me of Astral's crystal refinement.

**Comment by Zeure** [comment]
If you're still watching this, bro; my suggestion would be to keep what you want to keep.  The grading kinda sets you apart from similar mods; but it is much less consistent and of course people are going to reroll their bad parts, though that seems less like an exploit and more like a feature to me.  It's your mod, in the end.  My personal suggestion would be to just set everything to default grade and then allow supercharging to be how you power the tools up.

**Comment by ghost** [comment]
A "simple solution", for what it's worth, would be to disallow fragments to be recombined.

**Comment by bloche1871** [comment]
Personally I thought this feature had a lot of potential. I was planning on dealing with the recombining issue in my modpack by making it so that combining nuggets creates a "scrap metal" item which needs to be re-smelted into an ingot, that way there is a (fuel) cost to re-rolling. It would create an interesting automation challenge to the player to build a ore processing plant that uses fuel to "refine" all metal until the ingots are of a certain desired quality.

**Comment by SilentChaos512** [comment]
I've been thinking about just bringing grading back more or less as it was, but with a couple small changes. Part analyzer will have its name changed to "material grader" or "material analyzer" to make its function more obvious.

I do like the idea of adding a cost, as @bloche14 mentioned. As the mod is in 1.14, there is a catalyst slot for the part analyzer, but it's optional. Making the catalyst mandatory would make re-rolling feel like less of an exploit.

Another idea is to allowing re-rolling as a function of the grader. For example, put in an already graded material + catalyst and you get a chance at gaining a grade. Better catalysts will increase the chance.

**Comment by Thunder-Nova** [comment]
There is this mod called [Mine and Slash reloaded](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded). Perhaps using a skill tree of the sort could help. Maybe even make it compatible with that mod.

The grading and analyzing can become a player skill as well. Upgrading that skill can make better results. Deconstructing an analyzed gear could give random materials their analyzed bonuses, which prevents the next build to get analyzed again.
